#!/usr/bin/python3 -I
"""Use the desktop's native URI portal, keeping the browser outside the guard."""
import os
import sys
import gi
from gi.repository import Gio, GLib

if len(sys.argv) != 2:
    raise SystemExit('Usage: xdg-open URI-or-file')
bus = Gio.bus_get_sync(Gio.BusType.SESSION, None)
loop = GLib.MainLoop()
result = [1]
token = 'claude_' + str(os.getpid())
path = '/org/freedesktop/portal/desktop/request/' + bus.get_unique_name()[1:].replace('.', '_') + '/' + token

def response(connection, sender, object_path, interface, signal, parameters, data):
    result[0] = 0 if parameters.unpack()[0] == 0 else 1
    loop.quit()

bus.signal_subscribe('org.freedesktop.portal.Desktop', 'org.freedesktop.portal.Request',
                     'Response', path, None, Gio.DBusSignalFlags.NONE, response, None)
file = Gio.File.new_for_commandline_arg(sys.argv[1])
options = {'handle_token': GLib.Variant('s', token)}
if file.is_native():
    fd = os.open(file.get_path(), os.O_RDONLY | os.O_CLOEXEC)
    descriptors = Gio.UnixFDList.new()
    index = descriptors.append(fd)
    os.close(fd)
    bus.call_with_unix_fd_list_sync('org.freedesktop.portal.Desktop', '/org/freedesktop/portal/desktop',
        'org.freedesktop.portal.OpenURI', 'OpenFile', GLib.Variant('(sha{sv})', ('', index, options)),
        None, Gio.DBusCallFlags.NONE, 30000, descriptors, None)
else:
    bus.call_sync('org.freedesktop.portal.Desktop', '/org/freedesktop/portal/desktop',
        'org.freedesktop.portal.OpenURI', 'OpenURI', GLib.Variant('(ssa{sv})', ('', file.get_uri(), options)),
        None, Gio.DBusCallFlags.NONE, 30000, None)
loop.run()
raise SystemExit(result[0])
